window.LANG_INDEX_DE = {
    'hero-title': 'Schwanger werden ist keine Wissenschaft.',
    'hero-sub': 'Der Fruchtbarkeits-Tracker der einfach funktioniert. Klar, warm, komplett privat.',
    'cta-primary-text': 'Jetzt herunterladen',
    'cta-secondary-text': 'Mehr erfahren',
    'screenshot-note': 'Screenshots folgen bald',
    'features-title': 'Was die App kann',
    'f1-title': 'Zyklusverfolgung',
    'f1-desc': 'Alle 5 Phasen auf einen Blick. Follikelphase, Ovulation, Lutealphase und mehr.',
    'f2-title': 'Fertilitätsfenster',
    'f2-desc': 'Deine fruchtbaren Tage immer im Blick. Mit Vorhersage und täglichen Erinnerungen.',
    'f3-title': '100% Privat',
    'f3-desc': 'Kein Server, keine Cloud. Alle Daten bleiben ausschließlich auf deinem Gerät.',
    'f4-title': 'Nur du zählst',
    'f4-desc': 'Kein Content-Feed, keine Tipps, keine Ablenkung. Die App zeigt dir genau wo du stehst und wann dein Fenster offen ist.',
    'privacy-title': 'Dein Kinderwunsch bleibt privat. Versprochen.',
    'privacy-desc': 'Die App speichert alles lokal auf deinem Telefon. Kein Account, kein Server, keine Weitergabe an Dritte. Was du einträgst, bleibt bei dir.',
    'pricing-title': 'Ehrliche Preise',
    'pricing-sub': '7 Tage kostenlos testen. Kein Risiko.',
    'plan1-label': 'Monatlich',
    'plan1-sub': 'pro Monat',
    'plan1-annual': '= 17,88 \u20AC pro Jahr',
    'plan2-label': 'J\u00e4hrlich',
    'plan2-old': '11,99 \u20AC',
    'plan2-highlight': 'Spar 50% vs. monatlich',
    'plan2-limit': 'Nur f\u00fcr die ersten 1.000 Jahresabos',
    'badge-launch': 'Launch-Angebot',
    'urgency-text': 'Das Launch-Angebot gilt nur f\u00fcr die ersten 1.000 Jahresabos. Danach kehrt das Jahresabo zum regul\u00e4ren Preis zur\u00fcck.',
    'trial-note': 'Alle Pl\u00e4ne starten mit 7 Tagen kostenlosem Test. Keine Kreditkarte n\u00f6tig.',
    'cta-title': 'Bereit f\u00fcr euren n\u00e4chsten Schritt?',
    'cta-desc': 'Kostenlos starten, 7 Tage alles testen.',
    'final-btn': 'Im Play Store herunterladen',
    'final-note': 'Nur f\u00fcr Android. iOS folgt.',
    'footer-privacy': 'Datenschutz',
    'footer-imprint': 'Impressum',
    'launch-text': 'Launch im Play Store: 01.08.2026',
};
