window.LANG_INDEX_PT_BR = {
    'hero-title': 'Engravidar não é ciência exata.',
    'hero-sub': 'O rastreador de fertilidade que simplesmente funciona. Claro, acolhedor, totalmente privado.',
    'cta-primary-text': 'Baixar agora',
    'cta-secondary-text': 'Saiba mais',
    'screenshot-note': 'Capturas em breve',
    'features-title': 'O que o app faz',
    'f1-title': 'Acompanhamento do ciclo',
    'f1-desc': 'As 5 fases num só olhar. Fase folicular, ovulação, fase lútea e mais.',
    'f2-title': 'Janela fértil',
    'f2-desc': 'Seus dias férteis sempre à vista. Com previsão e lembretes diários.',
    'f3-title': '100% Privado',
    'f3-desc': 'Sem servidor, sem nuvem. Todos os dados ficam exclusivamente no seu dispositivo.',
    'f4-title': 'Dicas inteligentes',
    'f4-desc': '120 dicas sobre fertilidade, nutrição e rotina. Por fase e com calor humano.',
    'privacy-title': 'Seu desejo de engravidar fica privado. Prometido.',
    'privacy-desc': 'O app guarda tudo localmente no seu celular. Sem conta, sem servidor, sem compartilhamento com terceiros. O que você registra fica com você.',
    'pricing-title': 'Preços honestos',
    'pricing-sub': '7 dias de teste gratuito. Sem risco.',
    'plan1-label': 'Mensal',
    'plan1-sub': 'por mês',
    'plan1-annual': '= 17,88 \u20AC por ano',
    'plan2-label': 'Anual',
    'plan2-old': '11,99 \u20AC',
    'plan2-highlight': 'Economize 50% vs mensal',
    'plan2-limit': 'Apenas para as primeiras 1.000 assinaturas anuais',
    'badge-launch': 'Oferta de lançamento',
    'urgency-text': 'A oferta de lançamento vale apenas para as primeiras 1.000 assinaturas anuais. Depois, volta ao preço regular.',
    'trial-note': 'Todos os planos começam com 7 dias de teste gratuito. Sem cartão de crédito.',
    'cta-title': 'Prontos para o próximo passo de vocês?',
    'cta-desc': 'Comece grátis, teste tudo por 7 dias.',
    'final-btn': 'Baixar na Play Store',
    'final-note': 'Apenas para Android. iOS em breve.',
    'footer-privacy': 'Privacidade',
    'footer-imprint': 'Aviso legal',
    'launch-text': 'Lançamento na Play Store: 01.08.2026',
};
