window.LANG_INDEX_EN = {
    'hero-title': "Getting pregnant isn't rocket science.",
    'hero-sub': 'The fertility tracker that just works. Clear, warm, completely private.',
    'cta-primary-text': 'Download now',
    'cta-secondary-text': 'Learn more',
    'screenshot-note': 'Screenshots coming soon',
    'features-title': 'What the app does',
    'f1-title': 'Cycle tracking',
    'f1-desc': 'All 5 phases at a glance. Follicular phase, ovulation, luteal phase and more.',
    'f2-title': 'Fertility window',
    'f2-desc': 'Your fertile days always in view. With forecasts and daily reminders.',
    'f3-title': '100% Private',
    'f3-desc': 'No server, no cloud. All data stays exclusively on your device.',
    'f4-title': 'Journal',
    'f4-desc': 'Track moments, thoughts and feelings. Everything stored safely on your device.',
    'f5-title': 'Morning temperature',
    'f5-desc': 'Track your morning temperature to confirm ovulation more accurately.',
    'privacy-title': 'Your wish to conceive stays private. Promise.',
    'privacy-desc': 'The app stores everything locally on your phone. No account, no server, no third-party sharing. What you enter stays with you.',
    'cta-title': 'Ready for your next step?',
    'cta-desc': 'Start free, try everything for 30 days.',
    'final-btn': 'Download on Play Store',
    'final-note': 'Android only. iOS coming soon.',
    'no-free-title': 'Why there is no free version.',
    'no-free-p1': 'Many apps are free, but often you pay with something other than money: your own data.',
    'no-free-p2': 'When it comes to sensitive health data, privacy is not a given. Cycle data, temperature readings, personal entries, all of this belongs to the most intimate information there is.',
    'no-free-p3': 'That is why 1+1=3 works differently.',
    'no-free-b1': 'No ads',
    'no-free-b2': 'No tracking',
    'no-free-b3': 'No analysis',
    'no-free-b4': 'No sharing',
    'no-free-p4': 'Your data stays exclusively on your device and belongs only to you.',
    'no-free-p5': '1+1=3 costs a small amount because we will not let you pay with your data.',
    'no-free-tagline': 'The app is the product. Not you.',
    'footer-privacy': 'Privacy Policy',
    'footer-imprint': 'Imprint',
    'launch-text': 'Launching on Play Store: 01.08.2026'
};