window.LANG_INDEX_ES = {
    'hero-title': 'Quedarse embarazada no es ciencia exacta.',
    'hero-sub': 'El rastreador de fertilidad que simplemente funciona. Claro, cálido, completamente privado.',
    'cta-primary-text': 'Descargar ahora',
    'cta-secondary-text': 'Saber más',
    'screenshot-note': 'Capturas próximamente',
    'features-title': 'Qué hace la app',
    'f1-title': 'Seguimiento del ciclo',
    'f1-desc': 'Las 5 fases de un vistazo. Fase folicular, ovulación, fase lútea y más.',
    'f2-title': 'Ventana fértil',
    'f2-desc': 'Tus días fértiles siempre a la vista. Con predicción y recordatorios diarios.',
    'f3-title': '100% Privado',
    'f3-desc': 'Sin servidor, sin nube. Todos los datos permanecen exclusivamente en tu dispositivo.',
    'f4-title': 'Consejos inteligentes',
    'f4-desc': '120 consejos sobre fertilidad, nutrición y vida cotidiana. Por fase y con calidez.',
    'privacy-title': 'Tu deseo de ser madre queda en privado. Prometido.',
    'privacy-desc': 'La app guarda todo localmente en tu teléfono. Sin cuenta, sin servidor, sin compartir con terceros. Lo que introduces se queda contigo.',
    'pricing-title': 'Precios honestos',
    'pricing-sub': '7 días de prueba gratuita. Sin riesgo.',
    'plan1-label': 'Mensual',
    'plan1-sub': 'por mes',
    'plan1-annual': '= 17,88 \u20AC al a\u00f1o',
    'plan2-label': 'Anual',
    'plan2-old': '11,99 \u20AC',
    'plan2-highlight': 'Ahorra un 50% vs mensual',
    'plan2-limit': 'Solo para las primeras 1.000 suscripciones anuales',
    'badge-launch': 'Oferta de lanzamiento',
    'urgency-text': 'La oferta de lanzamiento es v\u00e1lida solo para las primeras 1.000 suscripciones anuales. Despu\u00e9s vuelve al precio regular.',
    'trial-note': 'Todos los planes comienzan con 7 d\u00edas de prueba gratuita. Sin tarjeta de cr\u00e9dito.',
    'cta-title': '\u00bfListos para vuestro pr\u00f3ximo paso?',
    'cta-desc': 'Empieza gratis, prueba todo durante 7 d\u00edas.',
    'final-btn': 'Descargar en Play Store',
    'final-note': 'Solo para Android. iOS pr\u00f3ximamente.',
    'footer-privacy': 'Privacidad',
    'footer-imprint': 'Aviso legal',
    'launch-text': 'Lanzamiento en Play Store: 01.08.2026',
};
