window.LANG_INDEX_DE = {
    'hero-title': 'Schwanger werden ist keine Wissenschaft.',
    'hero-sub': 'Der Fruchtbarkeits-Tracker der einfach funktioniert. Klar, warm, komplett privat.',
    'cta-primary-text': 'Jetzt herunterladen',
    'cta-secondary-text': 'Mehr erfahren',
    'screenshot-note': 'Screenshots folgen bald',
    'features-title': 'Was die App kann',
    'f1-title': 'Zyklusverfolgung',
    'f1-desc': 'Alle 5 Phasen auf einen Blick. Follikelphase, Ovulation, Lutealphase und mehr.',
    'f2-title': 'Fertilitätsfenster',
    'f2-desc': 'Deine fruchtbaren Tage immer im Blick. Mit Vorhersage und täglichen Erinnerungen.',
    'f3-title': '100% Privat',
    'f3-desc': 'Kein Server, keine Cloud. Alle Daten bleiben ausschließlich auf deinem Gerät.',
    'f4-title': 'Tagebuch',
    'f4-desc': 'Momente, Gedanken und Gefühle festhalten. Alles sicher auf deinem Gerät gespeichert.',,
    'f5-title': 'Morgentemperatur',
    'f5-desc': 'Morgentemperatur messen und den Eisprung noch genauer bestätigen.',,
    'privacy-title': 'Dein Kinderwunsch bleibt privat. Versprochen.',
    'privacy-desc': 'Die App speichert alles lokal auf deinem Telefon. Kein Account, kein Server, keine Weitergabe an Dritte. Was du einträgst, bleibt bei dir.',
    'cta-title': 'Bereit für euren nächsten Schritt?',
    'cta-desc': 'Kostenlos starten, 30 Tage alles testen.',
    'final-btn': 'Im Play Store herunterladen',
    'final-note': 'Nur für Android. iOS folgt.',
    'footer-privacy': 'Datenschutz',
    'footer-imprint': 'Impressum',
    'launch-text': 'Launch im Play Store: 01.08.2026',
};
