window.LANG_INDEX_ES = {
    'hero-title': 'Quedarse embarazada no es una ciencia.',
    'hero-sub': 'El monitor de fertilidad que simplemente funciona. Claro, cálido, completamente privado.',
    'cta-primary-text': 'Descargar ahora',
    'cta-secondary-text': 'Saber más',
    'screenshot-note': 'Capturas de pantalla próximamente',
    'features-title': 'Lo que hace la aplicación',
    'f1-title': 'Seguimiento del ciclo',
    'f1-desc': 'Las 5 fases de un vistazo. Fase folicular, ovulación, fase lútea y más.',
    'f2-title': 'Ventana fértil',
    'f2-desc': 'Tus días fértiles siempre a la vista. Con predicciones y recordatorios diarios.',
    'f3-title': '100% Privado',
    'f3-desc': 'Sin servidor, sin nube. Todos los datos permanecen exclusivamente en tu dispositivo.',
    'f4-title': 'Diario',
    'f4-desc': 'Registra momentos, pensamientos y sentimientos. Todo guardado de forma segura en tu dispositivo.',
    'f5-title': 'Temperatura matutina',
    'f5-desc': 'Mide tu temperatura matutina para confirmar la ovulación con mayor precisión.',
    'privacy-title': 'Tu deseo de tener un hijo permanece privado. Prometido.',
    'privacy-desc': 'La aplicación guarda todo localmente en tu teléfono. Sin cuenta, sin servidor, sin compartir con terceros. Lo que introduces, se queda contigo.',
    'cta-title': '¿Listos para vuestro próximo paso?',
    'cta-desc': 'Empieza gratis, pruébalo todo durante 30 días.',
    'final-btn': 'Descargar en Play Store',
    'final-note': 'Solo para Android. iOS próximamente.',
    'no-free-title': 'Por qué no hay una versión gratuita.',
    'no-free-p1': 'Muchas aplicaciones son gratuitas, pero a menudo se paga con algo diferente al dinero: tus propios datos.',
    'no-free-p2': 'Especialmente con datos de salud sensibles, la privacidad no está garantizada. Datos del ciclo, temperaturas, notas personales... todo esto pertenece a la información más íntima que existe.',
    'no-free-p3': 'Por eso 1+1=3 funciona de manera diferente.',
    'no-free-b1': 'Sin anuncios',
    'no-free-b2': 'Sin rastreo',
    'no-free-b3': 'Sin análisis',
    'no-free-b4': 'Sin compartir',
    'no-free-p4': 'Tus datos permanecen exclusivamente en tu dispositivo y solo te pertenecen a ti.',
    'no-free-p5': '1+1=3 tiene un coste pequeño porque no te hacemos pagar con tus datos.',
    'no-free-tagline': 'La aplicación es el producto. No tú.',
    'footer-privacy': 'Privacidad del sitio',
    'footer-app-privacy': 'Privacidad de App',
    'footer-imprint': 'Aviso Legal',
    'launch-text': 'Lanzamiento en Play Store: 01.08.2026'
};