window.LANG_INDEX_FR = {
    'hero-title': "Tomber enceinte, ce n'est pas sorcier.",
    'hero-sub': "Le moniteur de fertilité qui fonctionne tout simplement. Clair, chaleureux, complètement privé.",
    'cta-primary-text': 'Télécharger maintenant',
    'cta-secondary-text': 'En savoir plus',
    'screenshot-note': "Captures d'écran à venir",
    'features-title': "Ce que fait l'application",
    'f1-title': 'Suivi du cycle',
    'f1-desc': "Les 5 phases en un coup d'œil. Phase folliculaire, ovulation, phase lutéale et plus.",
    'f2-title': 'Fenêtre de fertilité',
    'f2-desc': 'Vos jours fertiles toujours sous les yeux. Avec prédictions et rappels quotidiens.',
    'f3-title': '100 % privée',
    'f3-desc': 'Pas de serveur, pas de cloud. Toutes les données restent exclusivement sur votre appareil.',
    'f4-title': 'Journal',
    'f4-desc': 'Notez vos moments, pensées et émotions. Tout est conservé en sécurité sur votre appareil.',
    'f5-title': 'Température matinale',
    'f5-desc': "Mesurez votre température matinale pour confirmer l'ovulation avec plus de précision.",
    'privacy-title': "Votre projet de grossesse reste privé. C'est promis.",
    'privacy-desc': "L'application stocke tout localement sur votre téléphone. Pas de compte, pas de serveur, pas de partage avec des tiers. Ce que vous saisissez reste chez vous.",
    'cta-title': 'Prêts pour votre prochaine étape ?',
    'cta-desc': 'Commencez gratuitement, testez tout pendant 30 jours.',
    'final-btn': 'Télécharger sur le Play Store',
    'final-note': 'Uniquement sur Android. iOS arrive bientôt.',
    'no-free-title': "Pourquoi il n'y a pas de version gratuite.",
    'no-free-p1': 'De nombreuses applications sont gratuites, mais on paie souvent avec autre chose que de l\'argent : ses propres données.',
    'no-free-p2': 'Quand il s\'agit de données de santé sensibles, la confidentialité ne va pas de soi. Données de cycle, relevés de température, notes personnelles... tout cela fait partie des informations les plus intimes qui soient.',
    'no-free-p3': 'C\'est pourquoi 1+1=3 fonctionne différemment.',
    'no-free-b1': 'Sans publicité',
    'no-free-b2': 'Sans suivi',
    'no-free-b3': 'Sans analyse',
    'no-free-b4': 'Sans partage',
    'no-free-p4': 'Vos données restent exclusivement sur votre appareil et n\'appartiennent qu\'à vous.',
    'no-free-p5': '1+1=3 coûte un petit montant parce que nous ne vous faisons pas payer avec vos données.',
    'no-free-tagline': 'L\'application est le produit. Pas vous.',
    'footer-privacy': 'Confidentialité Site',
    'footer-app-privacy': 'Confidentialité App',
    'footer-imprint': 'Mentions légales',
    'launch-text': 'Lancement sur le Play Store : 01/08/2026'
};