window.LANG_INDEX_DE = {
    'hero-title': 'Schwanger werden ist keine Wissenschaft.',
    'hero-sub': 'Der Fruchtbarkeits-Tracker der einfach funktioniert. Klar, warm, komplett privat.',
    'cta-primary-text': 'Jetzt herunterladen',
    'cta-secondary-text': 'Mehr erfahren',
    'screenshot-note': 'Screenshots folgen bald',
    'features-title': 'Was die App kann',
    'f1-title': 'Zyklusverfolgung',
    'f1-desc': 'Alle 5 Phasen auf einen Blick. Follikelphase, Ovulation, Lutealphase und mehr.',
    'f2-title': 'Fertilitätsfenster',
    'f2-desc': 'Deine fruchtbaren Tage immer im Blick. Mit Vorhersage und täglichen Erinnerungen.',
    'f3-title': '100% Privat',
    'f3-desc': 'Kein Server, keine Cloud. Alle Daten bleiben ausschließlich auf deinem Gerät.',
    'f4-title': 'Tagebuch',
    'f4-desc': 'Momente, Gedanken und Gefühle festhalten. Alles sicher auf deinem Gerät gespeichert.',,
    'f5-title': 'Morgentemperatur',
    'f5-desc': 'Morgentemperatur messen und den Eisprung noch genauer bestätigen.',,
    'privacy-title': 'Dein Kinderwunsch bleibt privat. Versprochen.',
    'privacy-desc': 'Die App speichert alles lokal auf deinem Telefon. Kein Account, kein Server, keine Weitergabe an Dritte. Was du einträgst, bleibt bei dir.',
    'cta-title': 'Bereit für euren nächsten Schritt?',
    'cta-desc': 'Kostenlos starten, 30 Tage alles testen.',
    'final-btn': 'Im Play Store herunterladen',
    'final-note': 'Nur für Android. iOS folgt.',
    'no-free-title': 'Warum es keine kostenlose Version gibt.',
    'no-free-p1': 'Viele Apps sind kostenlos, aber oft bezahlt man mit etwas anderem als Geld: den eigenen Daten.',
    'no-free-p2': 'Gerade bei sensiblen Gesundheitsdaten ist Privatsphäre nicht selbstverständlich. Zyklusdaten, Temperaturwerte, persönliche Einträge, all das gehört zu den intimsten Informationen überhaupt.',
    'no-free-p3': 'Deshalb funktioniert 1+1=3 anders.',
    'no-free-list': 'Keine Werbung. Kein Tracking. Keine Analyse. Keine Weitergabe.',
    'no-free-p4': 'Deine Daten bleiben ausschließlich auf deinem Gerät und gehören nur dir.',
    'no-free-p5': '1+1=3 kostet einen kleinen Betrag, weil wir nicht mit deinen Daten bezahlen lassen.',
    'no-free-tagline': 'Die App ist das Produkt. Nicht du.',
    'footer-privacy': 'Datenschutz',
    'footer-imprint': 'Impressum',
    'launch-text': 'Launch im Play Store: 01.08.2026',
};
