window.LANG_INDEX_PT_PT = {
    'hero-title': 'Engravidar não tem segredo.',
    'hero-sub': 'O monitor de fertilidade que simplesmente funciona. Claro, acolhedor, totalmente privado.',
    'cta-primary-text': 'Descarregar agora',
    'cta-secondary-text': 'Saiba mais',
    'screenshot-note': 'Capturas de ecrã em breve',
    'features-title': 'O que a app faz',
    'f1-title': 'Acompanhamento do ciclo',
    'f1-desc': 'As 5 fases num único lugar. Fase folicular, ovulação, fase lútea e mais.',
    'f2-title': 'Janela fértil',
    'f2-desc': 'Os teus dias férteis sempre à vista. Com previsões e lembretes diários.',
    'f3-title': '100% Privado',
    'f3-desc': 'Sem servidor, sem nuvem. Todos os dados ficam exclusivamente no teu dispositivo.',
    'f4-title': 'Diário',
    'f4-desc': 'Regista momentos, pensamentos e sentimentos. Tudo guardado em segurança no teu dispositivo.',
    'f5-title': 'Temperatura matinal',
    'f5-desc': 'Mede a tua temperatura matinal para confirmar a ovulação com mais precisão.',
    'privacy-title': 'O teu desejo de engravidar fica privado. Prometido.',
    'privacy-desc': 'A app guarda tudo localmente no teu telemóvel. Sem conta, sem servidor, sem partilha com terceiros. O que registas fica contigo.',
    'cta-title': 'Prontos para o vosso próximo passo?',
    'cta-desc': 'Começa grátis, testa tudo por 30 dias.',
    'final-btn': 'Descarregar na Play Store',
    'final-note': 'Apenas para Android. iOS em breve.',
    'no-free-title': 'Por que não há uma versão gratuita.',
    'no-free-p1': 'Muitas apps são gratuitas, mas muitas vezes pagas com algo diferente de dinheiro: os teus próprios dados.',
    'no-free-p2': 'Com dados de saúde sensíveis, a privacidade não é garantida. Dados do ciclo, temperaturas, registos pessoais... tudo isto pertence às informações mais íntimas que existem.',
    'no-free-p3': 'Por isso a 1+1=3 funciona de forma diferente.',
    'no-free-b1': 'Sem anúncios',
    'no-free-b2': 'Sem rastreio',
    'no-free-b3': 'Sem análise',
    'no-free-b4': 'Sem partilha',
    'no-free-p4': 'Os teus dados ficam exclusivamente no teu dispositivo e pertencem só a ti.',
    'no-free-p5': 'A 1+1=3 custa um valor pequeno porque não te fazemos pagar com os teus dados.',
    'no-free-tagline': 'A app é o produto. Não tu.',
    'footer-privacy': 'Privacidade',
    'footer-imprint': 'Aviso legal',
    'launch-text': 'Lançamento na Play Store: 01/08/2026'
};