window.LANG_INDEX_PT_BR = {
    'hero-title': 'Engravidar não é ciência exata.',
    'hero-sub': 'O rastreador de fertilidade que simplesmente funciona. Claro, acolhedor, totalmente privado.',
    'cta-primary-text': 'Baixar agora',
    'cta-secondary-text': 'Saiba mais',
    'screenshot-note': 'Capturas em breve',
    'features-title': 'O que o app faz',
    'f1-title': 'Acompanhamento do ciclo',
    'f1-desc': 'As 5 fases num só olhar. Fase folicular, ovulação, fase lútea e mais.',
    'f2-title': 'Janela fértil',
    'f2-desc': 'Seus dias férteis sempre à vista. Com previsão e lembretes diários.',
    'f3-title': '100% Privado',
    'f3-desc': 'Sem servidor, sem nuvem. Todos os dados ficam exclusivamente no seu dispositivo.',
    'f4-title': 'Diário',
    'f4-desc': 'Registre momentos, pensamentos e sentimentos. Tudo salvo com segurança no seu dispositivo.',,
    'f5-title': 'Temperatura matinal',
    'f5-desc': 'Meça sua temperatura matinal para confirmar a ovulação com mais precisão.',,
    'privacy-title': 'Seu desejo de engravidar fica privado. Prometido.',
    'privacy-desc': 'O app guarda tudo localmente no seu celular. Sem conta, sem servidor, sem compartilhamento com terceiros. O que você registra fica com você.',
    'cta-title': 'Prontos para o próximo passo de vocês?',
    'cta-desc': 'Comece grátis, teste tudo por 30 dias.',
    'final-btn': 'Baixar na Play Store',
    'final-note': 'Apenas para Android. iOS em breve.',
    'no-free-title': 'Por que não há versão gratuita.',
    'no-free-p1': 'Muitos apps são gratuitos, mas muitas vezes você paga com algo diferente de dinheiro: seus próprios dados.',
    'no-free-p2': 'Com dados de saúde sensíveis, a privacidade não é garantida. Dados do ciclo, temperaturas, registros pessoais, tudo isso pertence às informações mais íntimas que existem.',
    'no-free-p3': 'Por isso o 1+1=3 funciona de forma diferente.',
    'no-free-b1': 'Sem anúncios',
    'no-free-b2': 'Sem rastreamento',
    'no-free-b3': 'Sem análise',
    'no-free-b4': 'Sem compartilhamento',
    'no-free-p4': 'Seus dados ficam exclusivamente no seu dispositivo e pertencem só a você.',
    'no-free-p5': 'O 1+1=3 custa um valor pequeno porque não aceitamos que você pague com seus dados.',
    'no-free-tagline': 'O app é o produto. Não você.',
    'footer-privacy': 'Privacidade',
    'footer-imprint': 'Aviso legal',
    'launch-text': 'Lançamento na Play Store: 01.08.2026',
};
