window.LANG_INDEX_EN = {
    'hero-title': "Getting pregnant isn't rocket science.",
    'hero-sub': 'The fertility tracker that just works. Clear, warm, completely private.',
    'cta-primary-text': 'Download now',
    'cta-secondary-text': 'Learn more',
    'screenshot-note': 'Screenshots coming soon',
    'features-title': 'What the app does',
    'f1-title': 'Cycle tracking',
    'f1-desc': 'All 5 phases at a glance. Follicular phase, ovulation, luteal phase and more.',
    'f2-title': 'Fertility window',
    'f2-desc': 'Your fertile days always in view. With forecasts and daily reminders.',
    'f3-title': '100% Private',
    'f3-desc': 'No server, no cloud. All data stays exclusively on your device.',
    'f4-title': 'Journal',
    'f4-desc': 'Track moments, thoughts and feelings. Everything stored safely on your device.',,
    'f5-title': 'Morning temperature',
    'f5-desc': 'Track your morning temperature to confirm ovulation more accurately.',,
    'privacy-title': 'Your wish to conceive stays private. Promise.',
    'privacy-desc': 'The app stores everything locally on your phone. No account, no server, no third-party sharing. What you enter stays with you.',
    'cta-title': 'Ready for your next step?',
    'cta-desc': 'Start free, try everything for 30 days.',
    'final-btn': 'Download on Play Store',
    'final-note': 'Android only. iOS coming soon.',
    'footer-privacy': 'Privacy Policy',
    'footer-imprint': 'Imprint',
    'launch-text': 'Launching on Play Store: 01.08.2026',
};
