window.LANG_INDEX_IT = {
    'hero-title': 'Rimanere incinta non ha segreti.',
    'hero-sub': 'Il monitor della fertilità che funziona e basta. Chiaro, accogliente, completamente privato.',
    'cta-primary-text': 'Scarica ora',
    'cta-secondary-text': 'Scopri di più',
    'screenshot-note': 'Screenshot in arrivo',
    'features-title': "Cosa fa l'app",
    'f1-title': 'Monitoraggio del ciclo',
    'f1-desc': 'Tutte e 5 le fasi a colpo d\'occhio. Fase follicolare, ovulazione, fase luteale e altro.',
    'f2-title': 'Finestra fertile',
    'f2-desc': 'I tuoi giorni fertili sempre in vista. Con previsioni e promemoria quotidiani.',
    'f3-title': '100% Privato',
    'f3-desc': 'Nessun server, nessun cloud. Tutti i dati rimangono esclusivamente sul tuo dispositivo.',
    'f4-title': 'Diario',
    'f4-desc': 'Annota momenti, pensieri ed emozioni. Tutto custodito in sicurezza sul tuo dispositivo.',
    'f5-title': 'Temperatura mattutina',
    'f5-desc': 'Misura la tua temperatura mattutina per confermare l\'ovulazione con maggiore precisione.',
    'privacy-title': 'Il tuo desiderio di maternità resta privato. Promesso.',
    'privacy-desc': 'L\'app salva tutto localmente sul tuo telefono. Nessun account, nessun server, nessuna condivisione con terze parti. Quello che inserisci rimane solo tuo.',
    'cta-title': 'Pronti per il vostro prossimo passo?',
    'cta-desc': 'Inizia gratis, prova tutto per 30 giorni.',
    'final-btn': 'Scarica dal Play Store',
    'final-note': 'Solo per Android. iOS in arrivo.',
    'no-free-title': 'Perché non esiste una versione gratuita.',
    'no-free-p1': 'Molte app sono gratuite, ma spesso si paga con qualcosa di diverso dal denaro: i propri dati.',
    'no-free-p2': 'Quando si tratta di dati sanitari sensibili, la privacy non è scontata. Dati del ciclo, temperature, note personali... tutto questo fa parte delle informazioni più intime che esistano.',
    'no-free-p3': 'Ecco perché 1+1=3 funziona in modo diverso.',
    'no-free-b1': 'Nessuna pubblicità',
    'no-free-b2': 'Nessun tracciamento',
    'no-free-b3': 'Nessuna analisi',
    'no-free-b4': 'Nessuna condivisione',
    'no-free-p4': 'I tuoi dati rimangono esclusivamente sul tuo dispositivo e appartengono solo a te.',
    'no-free-p5': '1+1=3 ha un piccolo costo perché non ti facciamo pagare con i tuoi dati.',
    'no-free-tagline': 'L\'app è il prodotto. Non tu.',
    'footer-privacy': 'Privacy Sito',
    'footer-app-privacy': 'Privacy App',
    'footer-imprint': 'Note legali',
    'launch-text': 'Lancio sul Play Store: 01/08/2026'
};