window.LANG_INDEX_ES = {
    'hero-title': 'Quedarse embarazada no tiene ciencia.',
    'hero-sub': 'El monitor de fertilidad que simplemente funciona. Claro, cercano, completamente privado.',
    'cta-primary-text': 'Descargar ahora',
    'cta-secondary-text': 'Saber más',
    'screenshot-note': 'Capturas próximamente',
    'features-title': 'Qué hace la app',
    'f1-title': 'Seguimiento del ciclo',
    'f1-desc': 'Las 5 fases de un vistazo. Fase folicular, ovulación, fase lútea y más.',
    'f2-title': 'Ventana fértil',
    'f2-desc': 'Tus días fértiles siempre a la vista. Con predicción y recordatorios diarios.',
    'f3-title': '100% Privado',
    'f3-desc': 'Sin servidor, sin nube. Todos los datos permanecen exclusivamente en tu dispositivo.',
    'f4-title': 'Diario',
    'f4-desc': 'Anota momentos, pensamientos y sentimientos. Todo guardado de forma segura en tu dispositivo.',
    'f5-title': 'Temperatura matutina',
    'f5-desc': 'Mide tu temperatura matutina para confirmar la ovulación con más precisión.',
    'privacy-title': 'Tu deseo de ser madre queda en privado. Prometido.',
    'privacy-desc': 'La app guarda todo localmente en tu teléfono. Sin cuenta, sin servidor, sin compartir con terceros. Lo que introduces se queda contigo.',
    'cta-title': '¿Listos para vuestro próximo paso?',
    'cta-desc': 'Empieza gratis, prueba todo durante 30 días.',
    'final-btn': 'Descargar en Play Store',
    'final-note': 'Solo para Android. iOS próximamente.',
    'no-free-title': 'Por qué no hay versión gratuita.',
    'no-free-p1': 'Muchas apps son gratuitas, pero a menudo se paga con algo más que dinero: tus propios datos.',
    'no-free-p2': 'Con datos de salud sensibles, la privacidad no es algo garantizado. Datos del ciclo, temperaturas, entradas personales, todo eso pertenece a la información más íntima que existe.',
    'no-free-p3': 'Por eso 1+1=3 funciona de otra manera.',
    'no-free-b1': 'Sin publicidad',
    'no-free-b2': 'Sin rastreo',
    'no-free-b3': 'Sin análisis',
    'no-free-b4': 'Sin cesión',
    'no-free-p4': 'Tus datos permanecen exclusivamente en tu dispositivo y son solo tuyos.',
    'no-free-p5': '1+1=3 cuesta una pequeña cantidad porque no te hacemos pagar con tus datos.',
    'no-free-tagline': 'La app es el producto. No tú.',
    'footer-privacy': 'Privacidad',
    'footer-imprint': 'Aviso legal',
    'launch-text': 'Lanzamiento en Play Store: 01/08/2026'
};