window.LANG_INDEX_EN = {
    'hero-title': "Getting pregnant isn't rocket science.",
    'hero-sub': 'The fertility tracker that just works. Clear, warm, completely private.',
    'cta-primary-text': 'Download now',
    'cta-secondary-text': 'Learn more',
    'screenshot-note': 'Screenshots coming soon',
    'features-title': 'What the app does',
    'f1-title': 'Cycle tracking',
    'f1-desc': 'All 5 phases at a glance. Follicular phase, ovulation, luteal phase and more.',
    'f2-title': 'Fertility window',
    'f2-desc': 'Your fertile days always in view. With forecasts and daily reminders.',
    'f3-title': '100% Private',
    'f3-desc': 'No server, no cloud. All data stays exclusively on your device.',
    'f4-title': 'Just you',
    'f4-desc': 'No content feed, no tips, no noise. The app shows you exactly where you are and when your window opens.',
    'privacy-title': 'Your wish to conceive stays private. Promise.',
    'privacy-desc': 'The app stores everything locally on your phone. No account, no server, no third-party sharing. What you enter stays with you.',
    'pricing-title': 'Honest pricing',
    'pricing-sub': '7 days free trial. No risk.',
    'plan1-label': 'Monthly',
    'plan1-sub': 'per month',
    'plan1-annual': '= \u20AC17.88 per year',
    'plan2-label': 'Yearly',
    'plan2-old': '\u20AC11.99',
    'plan2-highlight': 'Save 50% vs monthly',
    'plan2-limit': 'For the first 1,000 yearly subscribers only',
    'badge-launch': 'Launch offer',
    'urgency-text': 'The launch offer is available for the first 1,000 yearly subscribers only. After that, the regular yearly price applies.',
    'trial-note': 'All plans start with a free 7-day trial. No credit card required.',
    'cta-title': 'Ready for your next step?',
    'cta-desc': 'Start free, try everything for 7 days.',
    'final-btn': 'Download on Play Store',
    'final-note': 'Android only. iOS coming soon.',
    'footer-privacy': 'Privacy Policy',
    'footer-imprint': 'Imprint',
    'launch-text': 'Launching on Play Store: 01.08.2026',
};
